name: Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/checkout@v6
        with:
          repository: clstrfsck/ludwig-system-test
          path: system-test

      - name: Set up Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2

      - name: Install system libraries
        run: sudo apt-get update && sudo apt-get install -y libncurses-dev libpcre2-dev

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install Python dependencies
        run: pip install -r system-test/requirements.txt

      - name: Run checks
        run: |
          zig build clean
          zig build build
          zig build build-release
          zig build test
          zig build system-test
